#!/bin/bash
CP_DIR="/home/neo/Desktop/cp"

show_help(){
    echo "
commands supported
    - new | -n : creates new and copies templates
    - run-input | -ri : g++ & ./a.out < input.txt  
    - run | -r : g++ & ./a.out
    - help | -h
    "
    exit 1
}


create_new(){

    if [ -z "${1}" ]
    then
        #not set
        fn="newFile"
    else
        #set
        fn=$1
    fi
    
    echo ${CP_DIR}
    ( cd ${CP_DIR} && touch "${fn}.cpp" && cat template.cpp >> "${fn}.cpp")
    
}

run_input(){
    cd ${CP_DIR}
    g++ "${1}" && echo "running .." && ./a.out < ./input.txt

}
# if [ $? -eq 0 ]
# then
#   echo "Successfully created file"
#   exit 0
# else
#   echo "Could not create file" >&2
#   exit 1
# fi
run(){
    g++ "${1}" && echo "running .." && ./a.out
}

# selects commands
case $1 in
    
    new|-n)
        create_new $2
    ;;
    run-input|-ri)
        run_input $2
    ;;
    run|-r)
        run $2
    ;;    
    help|-h)
        show_help
    ;;
    #nothing matched
    *)
        show_help
    ;;
    
esac